spring:
  datasource:
    url: ${PROD_DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health, info, promethus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: my-spring-app
  server:
    port: 8080

logging:
  level:
    root: info