spring:
  application:
    name: FinanceTrackerBackend
    version: 1.1
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    user:
      name: ${ADMIN_EMAIL}
      password: ${ADMIN_PASSWORD}
      roles: admin
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  endpoint:
    prometheus:
      access: unrestricted
    health:
      show-details: always
      cache:
        time-to-live: 0ms

    metrics:
      tags:
        application: FinanceTrackerBackend
server:
  port: 8080
admin:
  email: ${ADMIN_EMAIL}
  password: ${ADMIN_PASSWORD}
logging:
  logback:
    rollingpolicy:
      clean-history-on-start:
jwt_secret: ${JWT_SECRET}
bucket_size: 20

