spring:
  application:
    name: FinanceTrackerBackend
    version: 1.1
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    user:
      name: aice.smth@example.com
      password: SecurePass123!

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  endpoint:
    prometheus:
      access: unrestricted
      enabled: on
    health:
      show-details: always
      cache:
        time-to-live: 0ms
    metrics:
      tags:
        application: FinanceTrackerBackend

server:
  port: 8080

logging:
  logback:
    rollingpolicy:
      clean-history-on-start:
  file:
    name: C:\Users\lahce\IdeaProjects\FinanceTracker\FinanceTrackerBackend\src\main\resources\logs.log

jwt_secret: ${JWT_SECRET}
bucket_size: 20
