    spring:
    datasource:
      url: ${DEV_DB_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}

    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update

    data:
      redis:
        host: localhost
        port: 6379

  logging:
    level:
      sql: debug
      root: debug
      org.springframework: debug

