### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
GET localhost:8080/api/users
###
POST localhost:8080/api/users
Content-Type: application/json

{
  "username": "Lahcen8ahtat",
  "email": "lahe28ahtat@gmail.com",
  "password": "lahce22"
}
###
POST localhost:8080/api/accounts
Content-Type: application/json

{
  "accountName": "lahcenAhtat",
  "balance": 222,
  "user": {
    "id": 2122
  }
}
###
POST localhost:8080/api/auth/signup
Content-Type: application/json

{
  "firstname": "Alice",
  "lastname": "Smith",
  "email": "aice.smth@example.com",
  "password": "SecurePass123!"
}

###
POST localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "aice.smth@example.com",
  "rawPassword": "SecurePass123!"
}

