### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
GET localhost:8080/api/users
###
POST localhost:8080/api/users
Content-Type: application/json

{
  "username": "Lahcen8ahtat",
  "email": "lahe28ahtat@gmail.com",
  "password": "lahce22"
}
###
POST localhost:8080/api/accounts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhaWNlLnNtdGhAZXhhbXBsZS5jb20iLCJpZCI6IjIiLCJpYXQiOjE3NzA5OTQ0NjUsImV4cCI6MTc3MDk5NjI2NX0.pUAw2OdAzRwezlylVQ6iNIrL99vr43xt9uo30izSwsA

{
  "accountName": "Ahtat",
  "balance": 222,
  "user": {
    "id": 1
  }
}

###
POST localhost:8080/api/auth/signup
Content-Type: application/json

{
  "firstname": "Alice",
  "lastname": "Smith",
  "email": "aice.smth@example.com",
  "password": "SecurePass123!"
}

###
POST localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "aice.smth@example.com",
  "rawPassword": "SecurePass123!"
}
###
POST localhost:8080/api/transactions
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhaWNlLnNtdGhAZXhhbXBsZS5jb20iLCJpZCI6IjIiLCJpYXQiOjE3NzA5OTg1NzEsImV4cCI6MTc3MTAwMDM3MX0.3EEilvMAYmAMLyHFZZjouTSb29TU14sXl6Y8KKmA6Zo
POST localhost:8080/api/auth/signup
Content-Type: application/json

{
  "firstname": "Alice",
  "lastname": "Smith",
  "email": "aice.smth@example.com",
  "password": "SecurePass123!"
}

###
POST localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "aice.smth@example.com",
  "rawPassword": "SecurePass123!"
}

{
  "transaction": {
    "amount": 20,
    "transactionDate": "2025-02-03",
    "Description": "test",
    "Transactiontype":  "TRANSFER",
    "account": {
      "id": "2"
    }
  },
  "receiverId": "1",
  "senderId": "2"
}