### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
GET localhost:8080/api/users
Content-Type: application/json

{

}
###
POST localhost:8080/api/users
Content-Type: application/json

{
  "username": "Lah8ahta",
  "email": "lahe2aat@gmail.com",
  "password": "lace222"
}
###
POST localhost:8080/api/accounts
Content-Type: application/json

{
  "accountName": "lahcenAhtat",
  "balance": 222,
  "user": {
    "id": 2122
  }
}
###
DELETE localhost:8080/api/users/11
Content-Type: application/json


