create database  financetracker with owner postgres;
create table public.users
(
    user_id    bigint generated by default as identity
        primary key,
    email      varchar(50)  not null
        constraint uk6dotkott2kjsp8vw4d0m25fb7
            unique,
    password   varchar(100) not null,
    first_name varchar(50)  not null,
    last_name  varchar(50)  not null
);

alter table public.users
    owner to postgres;

create table public.accounts
(
    account_id   bigint generated by default as identity
        primary key,
    account_name varchar(100)     not null,
    balance      double precision not null,
    user_id      bigint
        constraint fknjuop33mo69pd79ctplkck40n
            references public.users
);

alter table public.accounts
    owner to postgres;

create table public.transactions
(
    transaction_id   bigint generated by default as identity
        primary key,
    description      varchar(255),
    transaction_type varchar(255)
        constraint transactions_transaction_type_check
            check ((transaction_type)::text = ANY
                   ((ARRAY ['INCOME'::character varying, 'EXPENSE'::character varying, 'TRANSFER'::character varying])::text[])),
    amount           double precision not null,
    date             date             not null,
    account_id       bigint           not null
        constraint fk20w7wsg13u9srbq3bd7chfxdh
            references public.accounts
);

alter table public.transactions
    owner to postgres;


insert into users (user_id,email, password, first_name, last_name) values (1,'lahcen','ahtat204','lahcen@asue24.org','lahce33');
insert into users (user_id,email, password, first_name, last_name) values (2,'mohamed','herewego','ahtmod@gmail','lah234gtgt3');
insert into accounts(account_id,account_name,balance,user_id) values (2,'testaccount',1346.22,1);
insert into accounts(account_id,account_name,balance,user_id) values (3,'testaccount2',1646.22,2);
insert into transactions(transaction_id,description, transaction_type, amount, date, account_id) VALUES(3,'test','EXPENSE',22.3,'2024-10-10',2);