drop table if exists users,transactions,accounts;
create database financetracker;
\c financetracker;
create table users
(
    user_id    bigint generated by default as identity
        primary key,
    email      varchar(50)  not null
        constraint uk6dotkott2kjsp8vw4d0m25fb7
            unique,
    password   varchar(100) not null,
    first_name varchar(50)  not null,
    last_name  varchar(50)  not null
);

create table accounts
(
    account_id   bigint generated by default as identity
        primary key,
    account_name varchar(100)     not null,
    balance      double precision not null,
    user_id      bigint
        constraint fknjuop33mo69pd79ctplkck40n
            references users
);



create table transactions
(
    transaction_id   bigint generated by default as identity
        primary key,
    description      varchar(255),
    transaction_type varchar(255)
        constraint transactions_transaction_type_check
            check ((transaction_type)::text = ANY
                   ((ARRAY ['INCOME'::character varying, 'EXPENSE'::character varying, 'TRANSFER'::character varying])::text[])),
    amount           double precision not null,
    date             date             not null,
    account_id       bigint           not null
        constraint fk20w7wsg13u9srbq3bd7chfxdh
            references accounts
);


select * from users,transactions,accounts;


